xuchen:
  module:
    request:
      log: true
      detail: true
      limit: true
    redis:
      prefix: demo:server
    log:
      enable-file: false
      project-name: server-demo
      level: info
      path: server-demo/logs
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 123456test
  redis:
    host: localhost
    password: password
    port: 16379
    database: 1
    timeout: 300
